### ISSUE TITLE
Yolo Network Training 계획

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#2]
- 데이터셋, 라벨링, 트레이닝, 테스트

**Comment by ChaejinE** [comment]
1. git clone https://github.com/JinFree/darknet.git
2. makefile 수정
  - cuda conpute capability -> NVIDIA Quadro RTX 4000 -> # ARCH= -gencode arch=compute_75,code=[sm_75,compute_75] 로 수정
3. DarNet 빌드 및 테스트
4. 데이터셋 준비 -> VOC 데이터셋 있음
5. git clone https://github.com/ssaru/convert2Yolo.git -> 이 저장소에 vocnames.txt 복사 후 여러 argument들 지정하고, 여기서 중요한건 --convert_output_path를 지정해 줘야한다.
   - vocnames.txt 는 class 이름 list 들이다.
6. 훈련 준비
   - pretrained - weights를 다운 받는다.
 7. voc 데이터셋에 맞게 수정한 cfg 파일을 준비한다.
   -  filter 수정 ( 5 + cls_num) * 3
   -  클래수 갯수 20으로 수정
 8. vocdata_colab 수정
   - classes = 20
   - train path 수정, names path 수정, backup path 수정( backup path는 weights 파일이 저장되는 경로다. )
 9. 학습 진행

**Comment by ChaejinE** [comment]
바꿔줘야 하는 부분 or 중요 부분
1. Makefile (computing capability 설정 part)
2. convert2Yolo (data convert part)
3. pretrained download
4. cfg (filter, class num 수정)
5. vocdata_colab.txt 파일 수정 (class num, train_path, names_path, backup_path)

**Comment by eunji9128** [comment]
FYI, you can check 'cuda compute capability' for makefile modification in below:
[https://developer.nvidia.com/cuda-gpus#compute](url)

**Comment by eunji9128** [comment]
FYI, why is the number of filters calculated as (5 + the number of classes) * 3
-----------------------------------------------------------------------------------------------
filters = (classes + 5) * number of masks in one yolo layer

          = (classes + width + height + x + y + confidence) * number of masks in one yolo layer

          = (classes + 1+1+1+1+1) * 3

==> Yolov3은 grid cell마다 3개의 박스를 detect하므로 filters = (classes + 5) * 3
