### ISSUE TITLE
AWS 상에서 옴니버스 돌리기

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#23]
# NGC
- https://www.nvidia.com/en-us/gpu-cloud
# 설치 순서
1. AWS 에 가입한다.
- [AWS](https://aws.amazon.com/ko/free/?trk=ps_a134p000003yHYmAAM&trkCampaign=acq_paid_search_brand&sc_channel=PS&sc_campaign=acquisition_KR&sc_publisher=Google&sc_category=Core-Main&sc_country=KR&sc_geo=APAC&sc_outcome=acq&sc_detail=aws&sc_content=Brand_Core_aws_e&sc_segment=444218215904&sc_medium=ACQ-P|PS-GO|Brand|Desktop|SU|Core-Main|Core|KR|EN|Text&s_kwcid=AL!4422!3!444218215904!e!!g!!aws&ef_id=Cj0KCQjw9O6HBhCrARIsADx5qCToZpVMQATfPUZAzCRlsGzhRwmhOB8BzSBdprJA79xJE9poHvVEpqcaAnfNEALw_wcB:G:s&s_kwcid=AL!4422!3!444218215904!e!!g!!aws&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)
2. 로그인 후 가상머신 시작 (EC2)
3. AMI Community에서 isaacsim 검색
- 최신 가상 이미지를 선택헀다.
4. g4dn type 선택
- vCPU : 16, Memory : 64 Gb

**Comment by eunji9128** [comment]
https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/setup.html

**Comment by eunji9128** [comment]
Connect to System Monitor by opening http://localhost:3080/ in a web browser. Check that all apps are listed as ‘Running’

**Comment by chocoJiyeon** [comment]
저는 서울을 선택하고 했음.
g4dn .4xlarge 선택
보안에서는 ip설정에서 all 선택해서 0.0.0.0 으로
새로운 키 이름은 : Loc JY Key -->프라이빗 키파일 LocJYKey.pem 다운받음.
이케 하면 실패 뜸.... 실패 메세지는 아래와 같다ㅠㅠ
```
Your request for accessing resources in this region is being validated, and you will not be able to launch additional resources in this region until the validation is complete. We will notify you by email once your request has been validated. While normally resolved within minutes, please allow up to 4 hours for this process to complete. If the issue still persists, please let us know by writing to aws-verification@amazon.com for further assistance.
```

**Comment by chocoJiyeon** [comment]
다시 해봤을 땐 이렇게 뜸.

You have requested more vCPU capacity than your current vCPU limit of 0 allows for the instance bucket that the specified instance type belongs to. 
Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.

free tier를 넘쳤다고 한다...

**Comment by chocoJiyeon** [comment]
보안설정에서 ip를 all 이 아니라 내 아이피로 설정하고 다시 해봤지만

같은 에러가 떴다.. 이게 문제가 아닌 듯

**Comment by chocoJiyeon** [comment]
![image](https://user-images.githubusercontent.com/61004887/127020408-513f0972-3acf-4756-b507-91838f10cb8d.png)

**Comment by chocoJiyeon** [comment]
서울에서는 g 인스턴스 16을 늘려준다고 함.
아래는 답변 내용

![image](https://user-images.githubusercontent.com/61004887/127266971-7e00d20a-e33b-4150-a436-7a5075d505a4.png)

**Comment by ChaejinE** [comment]
![image](https://user-images.githubusercontent.com/69780812/127268740-ba8ee60b-1ee4-4097-8c6d-a313472ff7f2.png)
저도 4개 받았습니다. 저는 저녁에 돌려볼게요

**Comment by chocoJiyeon** [comment]
![image](https://user-images.githubusercontent.com/61004887/127308462-fc7e9a79-3934-4b22-9a38-3dfd6c66b2bd.png)

옴니버스 닥스 보고 인스턴스 생성함

**Comment by chocoJiyeon** [comment]
근데 connect 가 안됨....
![image](https://user-images.githubusercontent.com/61004887/127319624-c00f0007-13f0-446a-ae99-548c04643c04.png)

계속 이렇게 뜸.

**Comment by chocoJiyeon** [comment]
![image](https://user-images.githubusercontent.com/61004887/127319910-5abe6ad2-60c4-4882-b14e-9e377c013b4e.png)
왼쪽 맨 위에 보면 New EC2 Experience 왼쪽에 뭐 클릭할수 있는거 있는데 
그거 클릭하구 하니까 설명서처럼 됨!!!!

**Comment by chocoJiyeon** [comment]
**puTTY 커멘드창에서 다운로드 하는 방법**

1. sudo apt-get install openssh-server
2. /etc/init.d/ssh start 
3. sudo apt-get install putty
4. putty 입력하면 실행됨.

**Comment by chocoJiyeon** [comment]
puTTY 에 받아놓았던 키를 넣으면 안됨....실패 뜸

![image](https://user-images.githubusercontent.com/61004887/127327306-f4f5759b-42ce-4391-a39d-d0cc7fc55d85.png)
처음에 aws 인스턴트 신청하면서 윈도우에서 했는데, 윈도우에서 키를 받았어서 안되는거 같아서
다시 키를 받아서 해보려고 한다.....

**Comment by chocoJiyeon** [comment]
안되는 이유 뭔가 알거 같다!!!!
인스턴스 만들면서 지역 설정이 잘못된듯??

**Comment by ChaejinE** [comment]
오  저도 보면서 뭔일있으면 적어놀게요
지금 아이작 사이트하고있어서 개념 정리되면 시도해보겠음
우분투에서 하면 푸티안받고 터미널쓰면되여

**Comment by chocoJiyeon** [comment]
![image](https://user-images.githubusercontent.com/61004887/127517433-cae29d3f-55b4-471e-a32d-88a239e70f57.png)


이거 성공인가요???
-------------------------------

**Comment by chocoJiyeon** [comment]
아이작심 실행하는거 코드 입력했는데 아래처럼 되고 멈췄는데 아무것도 안켜짐.....기다려야하는건가.......

![image](https://user-images.githubusercontent.com/61004887/127520508-039a499f-fec5-4e3d-a984-8378ea045c51.png)

**Comment by ChaejinE** [comment]
# 인스턴스 받음
![image](https://user-images.githubusercontent.com/69780812/127585653-c2de735a-13d6-4589-a614-cceae3c023ce.png)
vCPU 4개밖에안줌..

**Comment by chocoJiyeon** [comment]
windowed container 로 실행하려고 하면
(명령어 : sudo docker run --entrypoint ./runapp.sh --gpus all -e "ACCEPT_EULA=Y" --rm --network=host -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/localtime:/etc/localtime:ro -e DISPLAY=unix${DISPLAY} nvcr.io/nvidia/isaac-sim:2021.1.1)
아래와 같이 Fatal 이라구 뜸...
![image](https://user-images.githubusercontent.com/61004887/127591724-32a0d0a7-d1fd-41df-8884-7c2f7c9f66cf.png)

**Comment by chocoJiyeon** [comment]
ami 상에서 원래 노트북에 했던거 처럼 아이작심 설치하는거 처음부터 설치하구 따라해봤는데 안된다.
windowed container 로 하려고 하면 안되는듯.

클라우드 상에서 하는게 맞는거 같은데,,, 실행도 되는데 눈에 안보이는거 같아서?
왜냐면 커멘드창 보면 마지막ㅇㅔ nucleus server 를 체크하라고 되있으니까
 localhost/8080 똑같이 들어가봤는데....
![image](https://user-images.githubusercontent.com/61004887/127776802-34085a3d-68bb-4e49-bad3-4ee291db3dba.png)

이게 그냥 예전에 내가 만들어 놓은 건지
연결이 된건지 아직 잘 모르겠다.
오늘도 여전히 모르겠다....
