### ISSUE TITLE
Navigation Master Test

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#25]
# 문제점
- 컴퓨팅 파워 부족으로 Rviz 실행이 불가능
# 시도
- 다른 컴퓨터에서 SLave 형태로 접근해보자.
- 다른 컴퓨터 : Rviz, Docker : omniverse
# 실행 순서
1. docker roscore Master URI 지정
2. Master URI docker 쪽으로 지정
3. local 컴퓨터 carter rviz 실행
4. docker 확인 
# 재시도
- docker와 내 컴퓨터 ssh를 깔아서 시도
  - ssh 문제였는지는 모르겠지만.. 젯슨보드로 토픽 통신 확인
  - docker ip 와 local ip중 local ip 에서만 ros 통신이 이뤄진 것을 확인했다.
1. Slave catkin workspace 에서 move_base.launch 실행
2. docker 에서 확인 (옴니버스)

**Comment by eunji9128** [comment]
https://github.com/PolytechAngersMecatroniqueClub/Tutorials/wiki/6-Using-ROS-with-the-Raspberry

**Comment by ChaejinE** [comment]
![image](https://user-images.githubusercontent.com/69780812/126990552-315fdd3c-76b2-472f-afe4-606b1d86fbf8.png)

젯슨보드에서 감당이 안되는 것으로 보인다.
자세한 원인은 내일 검색해보려한다.

**Comment by ChaejinE** [comment]
# docker bashrc export 상태
![image](https://user-images.githubusercontent.com/69780812/126990792-6aefd0dd-c4d0-4510-9f28-233f7b065d66.png)

**Comment by ChaejinE** [comment]
![image](https://user-images.githubusercontent.com/69780812/126993439-b702434d-4140-492c-a9a4-9d951c373218.png)

![image](https://user-images.githubusercontent.com/69780812/126993476-d7cefa9d-a604-4baa-b43d-5995ec624992.png)

- 이미 깔려있는데 rospack find 해도 찾을수가 없다고 한다..
- rviz .. Tx2에서는 안되는 것인가 ..?

![image](https://user-images.githubusercontent.com/69780812/126993638-63c68515-0eae-4460-b03f-5b9bf8b522ba.png)

**Comment by eunji9128** [comment]
![image](https://user-images.githubusercontent.com/80051721/126994527-c8a77624-bab7-485f-a31a-5e9767d0b770.png)
Docker 내부에서 ROS 실행했을 때 에러

**Comment by eunji9128** [comment]
/opt/ros/melodic/share/rviz
/opt/ros/melodic/     setup.bash
있는지 확인

**Comment by ChaejinE** [comment]
> /opt/ros/melodic/share/rviz
> /opt/ros/melodic/ setup.bash
> 있는지 확인

Thanks eun
