### ISSUE TITLE
issac sight 공부 및 실습

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#28]
# 목표
- sight documentation 을 통해 개념을 확립한다.
- isaac bazel navigation 실습을 통해 활용법을 숙지 및 고민한다.
# 참고 링크
- [sight docs](https://docs.nvidia.com/isaac/isaac/packages/sight/index.html)
- [omniverse 에서 실습](https://docs.nvidia.com/isaac/isaac/doc/simulation/ovkit.html)

**Comment by ChaejinE** [comment]
- omniverse 실습을 위해서는 isaac sdk 가 있어야한다.
- [다운로드 링크](https://developer.nvidia.com/isaac/downloads)

**Comment by ChaejinE** [comment]
isaac sdk 설치시 docker에서 오류가 해결되었는데,
root에 setup 하면안되고, home 같은 곳에서 깔아야 한다.
Warning이 뜨긴했는데, 무시하면 bazelrc 라는 파일을 찾을 수 없게되는 문제가 있었다.

**Comment by ChaejinE** [comment]
# Error  상황
![image](https://user-images.githubusercontent.com/69780812/127493406-4847ffd9-000e-40a1-a4d2-5250c169242c.png)
![image](https://user-images.githubusercontent.com/69780812/127493227-906df2d5-e9bf-4595-ac67-54faa1a9f493.png)
![image](https://user-images.githubusercontent.com/69780812/127493272-97f69c8b-d7a5-41ab-8686-0dba5fe16272.png)

**Comment by ChaejinE** [comment]
https://forums.developer.nvidia.com/t/isaac-sim-2019-2-warehouse-scene-navigation-isaac-application-terminated-unexpectedly/79353
위 링크 참고중

**Comment by ChaejinE** [comment]
위는 나와 다른 에러 인거 같아서 pass
https://forums.developer.nvidia.com/t/isaac-sdk-2019-3-isaac-application-terminated-unexpectedly/112307/2
위 링크 참고중 (나와 같은 에러)

**Comment by ChaejinE** [comment]
Is /usr/local/cuda/lib64 included in the LD_LIBRARY_PATH environment variable?
부분에서 위 경로가 없으며 nvcc -V 해도 안됐음. cuda가 없는 것으로 판별됨.

isaac-sim docker에 cuda 가 없어서 cuda 갈아 보는중

**Comment by eunji9128** [comment]
"ACCEPT_EULA=Y"

**Comment by ChaejinE** [comment]
- 기존 cuda 10.2 까는 방법이 CLI에 EULA accept 하는 창이 떠야하는데.. docker 라서 뜨지 않는거 같다..
- 시도 1. 다른 10.2 까는 방법으로 설치했지만, 바로 충돌 났다.
  - driver와 cuda 버전이 충돌 나버려서 내일 EULA accept 하는 방법 없이 cuda 10.2를 깔아보는 것을 시도할 예정

**Comment by ChaejinE** [comment]
# CUDA 10.2 도커에 설치 완료
https://github.com/ChaejinE/HanComTermProject/issues/13
예전에 은지누나가 알려준 사이트에서 cuda 설치를 시도했다.
xhost +local:을 꼭해줘야 DISPLAY가 되는 것인지 순서대로 해보니 됐다. 설명대로 잘 설치 완료

**Comment by ChaejinE** [comment]
# CUDA 10.2 이미지 Upload 완료
![image](https://user-images.githubusercontent.com/69780812/127535025-32ebf583-68a5-450b-abe3-a5f0119116fa.png)
- 진짜.. 할짓이 안되는 것 같아서 새로 도커 이미지를 떠 놓았다. 
  - lotto-cuda10.2 가 이미지 이름이다. NVIDIA driver + CUDA 10.2가 필요한 경우에는 저 이미지로 run 하면 된다.
```shell
sudo docker run --gpus all -e "ACCEPT_EULA=Y" -v ~/docker/isaac-sim/samples:/isaac-sim/exts/omni.isaac.samples/omni/isaac/samples -v ~/docker/isaac-sim/python_samples:/isaac-sim/python_samples -v ~/docker/isaac-sim/ros_samples:/isaac-sim/ros_samples -v ~/docker/isaac-sim/ros2_samples:/isaac-sim/ros2_samples -v ~/docker/isaac-sim/documents:/root/Documents:rw -v ~/docker/isaac-sim/cache:/root/.cache/ov:rw -v ~/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw -v ~/docker/isaac-sim/data:/root/.local/share/ov/data:rw --network=host lotto-cuda10.2:0.1
```
- **lotto-cuda10.2:0.1** 가 실행할 이미지명:태그 라는 것을 잊지말자.
  - v 옵션에서 ROS는 localhost, docker 경로에 있는 ros_sample 끼리 -v 볼륨 인자로 마운트해서 실행하도록 할 예정이다.
- TODO로 추가적으로 ROS 설치된 이미지도 만들어 놔야겠다.
-

**Comment by ChaejinE** [comment]
https://hancomacademy-opb.my.webex.com/webappng/sites/hancomacademy-opb.my/meeting/download/3dbabe60233fef5b35b8af5f8334807e

**Comment by ChaejinE** [comment]
http://hancom.crewcloud.net/UI/WorkingTime/

**Comment by ChaejinE** [comment]
![image](https://user-images.githubusercontent.com/69780812/127581173-ccbc963b-fee3-41e5-a186-4f457c4f4147.png)
그런데 왜왜 갑자기 이렇게 됐는지 ..

**Comment by ChaejinE** [comment]
```shell
cd /home/user/HanComTermProject/run_docker
lotto-cuda10_2.sh
```
- tmux new -s isaac 해서
- tmux attach -t issac
  - 위를 통해 tmux 세션에 들어가서 실행해주면 된다.

**Comment by ChaejinE** [comment]
이제 다시 Isaac sdk 설치

**Comment by ChaejinE** [comment]
![image](https://user-images.githubusercontent.com/69780812/127593749-585c0fc5-5269-4469-a30e-c563331f9e6e.png)
- 참고 링크 : https://blog.csdn.net/asia66/article/details/97107404

![image](https://user-images.githubusercontent.com/69780812/127593771-8bd1a36e-f565-4535-b8f3-a3a80ad173b3.png)
- 참고 링크 : https://github.com/phusion/baseimage-docker/issues/319

**Comment by ChaejinE** [comment]
# docker 유용한 인자들 정리 된 링크
https://mg-laboratory.tistory.com/122

**Comment by ChaejinE** [comment]
위 에러 대응 링크들을 깔지 않고, ~ 디렉토리에 isaac sdk를 설치했는데 잘되는가 싶더니 안된다..
위 링크들을 깔아보고 다시 해보자

**Comment by ChaejinE** [comment]
# Error
- 바젤 못찾는다고 나오는 것에 대한 링크 참조 해볼 것
https://forums.developer.nvidia.com/t/fatal-unexpected-error-reading-blazerc-file-bazelrc/164170

**Comment by ChaejinE** [comment]
# 현재상황
- isaac sdk 를 tar 파일일 때부터 docker container 에서 /home 디렉토리에서 디펜던시를 설치했다.
![image](https://user-images.githubusercontent.com/69780812/127603529-4133f3ab-fcc5-4120-a61a-6f8b498420ab.png)

**Comment by ChaejinE** [comment]
# 성공 !
![image](https://user-images.githubusercontent.com/69780812/127606137-1267b9c6-826f-471b-ad7e-0c9e09ed567b.png)

**Comment by ChaejinE** [comment]
# 무엇이 필요 했나 ?
1. isaac sdk
2. root 가 아니라 /home에 설치해야됐다.
   - 여기에 tar 파일을 풀어야 된다.
3. cuda 10.2

**Comment by eunji9128** [comment]
튜토리얼 중에 robot engine bridge start 하라는 게 있는데 아래 링크 참조인 듯
https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/ext_omni_isaac_robot_engine_bridge.html
