### ISSUE TITLE
aws 이용해서 create 실행하기

### ISSUE THREAD

**Issue by chocoJiyeon** [ChaejinE/HanComTermProject#33]
현재 상황 : aws에서 인스턴스 만들어서 연결한 커멘드창에서 원래 컴퓨터에 깔려있는 옴니버스를 실행시켜 봤는데 여전히 gpu가 맞지 않는다고 뜬다.

**Comment by chocoJiyeon** [comment]
![image](https://user-images.githubusercontent.com/61004887/127980493-04777aac-287e-48b7-ac66-e16749bd41b6.png)

아이작 심이 깔려 있다...
근데 실행은 어케 하지?

**Comment by ChaejinE** [comment]
> 현재 상황 : aws에서 인스턴스 만들어서 연결한 커멘드창에서 원래 컴퓨터에 깔려있는 옴니버스를 실행시켜 봤는데 여전히 gpu가 맞지 않는다고 뜬다.

gpu mismatching error 라면
cuda 와 드라이버가 맞지 않아서 나는 에러입니다.

**Comment by chocoJiyeon** [comment]
vnc 서버 이용해서 해보려고 했는데

![image](https://user-images.githubusercontent.com/61004887/128001966-9b1b35d3-4d43-47e1-bcd9-9c3b30ded8e4.png)
타임아웃 뜨고 연결이 안됨.

제 컴터에서 vnc로 aws인스턴스 연결한 아이피에 접근하는거 맞나요?
그렇게 했는데 안되서...

**Comment by chocoJiyeon** [comment]
aws 인스턴스에 설치되어 있는 쿠다, 그래픽드라이버 정보

![image](https://user-images.githubusercontent.com/61004887/128010166-f5344c28-7f36-4e7d-98e3-505aad6e4850.png)

**Comment by chocoJiyeon** [comment]
옮겼다!!!!!!

![image](https://user-images.githubusercontent.com/61004887/128025305-4ecde147-49ac-4df5-9228-c8d6ba5fe9bf.png)

**Comment by chocoJiyeon** [comment]
설정 다하고 보안그룹도 이렇게 했는ㄷㅔ.......연결ㅇㅣ 안된ㄷㅏ

![image](https://user-images.githubusercontent.com/61004887/128116821-8c3a9cca-e46e-4799-8c91-978b8b76d072.png)

**Comment by chocoJiyeon** [comment]
옴니버스 실행 오류
![image](https://user-images.githubusercontent.com/61004887/128126128-ba6b1b62-848e-46bd-8ac6-bb474e10361a.png)

나와 같은 오류 링크
https://forums.developer.nvidia.com/t/launcher-installation-fails-on-ubuntu-linux/174074
