### ISSUE TITLE
Isaac-sim + ROS april_tag tutorial test

### ISSUE THREAD

**Issue by eunji9128** [ChaejinE/HanComTermProject#34]
### ROS bridge 준비 (pre)
- server com 에서 터미널 오픈
  - ``` source /opt/ros/melodic/setup.bash ``` 실행
- 사용할 workspace 생성
  - ``` mkdir -p ~/catkin_ws/src ```
  - ``` cd ~/catkin_ws/src ```
- 사용할 ros_samples 패키지들을 workspace로 복사하기 위해 아래 명령어 실행
  - ```cp -r ./local/share/ov/pkg/issac__sim-2021.1.1/ros_samples ~/catkin_ws/src/```
-  패키지 디펜던시 확인을 위해 rosdep 실행 + catkin_make
  - ```cd ~/catkin_ws```
  - ```rosdep install --from-paths src --ignore-src --rosdistro=melodic```
  - ```catkin_make```
  - ```source devel/setup.bash```
- ROS_MASTER_URI 설정 후 roscore 실행
  - ```ifconfig```
  - ```ip 확인(ethernet 아님 wlp) = master ip로 쓸 거```
  - ```export ROS_MASTER_URI=http://[master_ip]:11311```
  - ```roscore```

### ISAAC-SIM docker 준비
- server com에서 새로운 터미널 오픈
- 이전에 채진이가 저장해놓은 Isaac-sim docker image 사용(cuda10.2 + isaac_sdk + ros available)
  - ```cd ~/HanComTermProject/run_docker```
  - ``` sh lotto-ros.sh```
- Isaac-sim 오픈 확인

### ROS bridge 준비(post)
- server com에서 새로운 터미널 오픈
- 위에서 실행한 isaac-sim docker container id 확인 후 실행
  - ```docker ps -l```
  - ```isaac-sim docker container id 확인```
  - ```docker exec -it [container_id] bash```
- 터미널 커맨더가 $ 에서 #으로 바뀌었는지 확인 > # 이면 container 실행 중
- ROS bridge extension 을 실행하기 위한 디펜던시 설치
  - ```apt-get install libapr1 lsb-release -y```
  - ```sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'```
  - ```apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654```
  - ```apt update && apt install ros-melodic-ros-base -y```
- ROS IP 설정
  - docker ip 확인
    - ```apt-get install net-tools # ifconfig 없을 때 ```
    - ```ifconfig```
    - ```docker0 의 ip 확인```
  - 환경 변수에 입력
    - ```export ROS_IP=[docker0_ip]```
    - ```export ROS_MASTER_URI=http://[master_ip]:11311```
 

### Isaac-sim 에서 예제 실행
- 위에서 실행했던 Isaac-sim UI에서 예제 실행
  - Isaac Examples -> Communicating -> ROS -> April Tag
- 왼쪽 Play 실행
- 결과 화면
- ![image](https://user-images.githubusercontent.com/80051721/128025827-0dda9901-2001-41e1-b193-d5d328025c19.png)

### ROS launch 실행(AR code 인식을 위한 소스)
- server com에서 새로운 터미널 오픈
- apriltag_ros 패키지 설치
  - ```sudo apt install ros-melodic-apriltag-ros```
- catkin_make, source devel/setup.bash 다 해줌
- roslaunch 실행
  - ```cd ~/catkin_ws/src/ros_samples/april_tag```
  - ```roslaunch continuous_detection.launch```

### Rviz 실행(detection 결과 확인)
- server com에서 새로운 터미널 오픈
- Rviz 통해서 실행
  - ```rosrun rviz rviz -d ~/catkin_ws/src/ros_samples/april_tag/config.rviz```
- 결과 화면
- ![image](https://user-images.githubusercontent.com/80051721/128025635-1d858f2a-69b7-4333-81d3-ea7c0f840f14.png)

### 터미널에서 Detection raw data 확인
- server com에서 새로운 터미널 오픈
- echo 통해 데이터 확인
  - ```rostopic echo tag_detections```
- 결과 화면
- ![image](https://user-images.githubusercontent.com/80051721/128025752-0fc7e17d-2ec4-4326-9e90-afac339ae667.png)

**Comment by ChaejinE** [comment]
# 설치해야되는 것
```shell
sudo apt install ros-melodic-apriltag-ros
```
# 돌리고 있는 상황
1. roscore : server local
2. rospkg code : server local
3. isaac-sim : docker container
