### ISSUE TITLE
Isaac-sim + ROS stereo tutorial test

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#35]
# 설치해야되는 것
없었음
# 돌리고 있는 상황
1. roscore : server local
2. rospkg code : server local
3. isaac-sim : docker container

**Comment by eunji9128** [comment]
### 튜토리얼 링크
- https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/sample_ros_stereo.html


### What I carried out
- 아래에서 server-com terminal = [ST], docker ISAAC-sim terminal = [DT] 로 명명
- [ST] roscore 실행 중
- [DT] isaac-sim docker 실행 중
- [DT] isaac-sim ui 열리고 isaac_example > communication > ROS > stereo 열기
- [DT] stereo 예제 열리면 아래와 같이 설정
- Stage window에서 /World/Carter_ROS/ROS_Camera_Stereo_Right 선택 후 Raw USD Properties 안의 enabled 체크
- ![image](https://docs.omniverse.nvidia.com/app_isaacsim/_images/isaac_ros_sample_stereo_1.png)
- Play 클릭
- viewport 2개 뜨는 데 드래그 하면 파란 박스 나타남 원하는 위치에 가서 드래그 놓으면 윈도우 배치 가능
- [new ST] rosrun rviz rviz -d {user가 저장한 dir}/ros_samples/stereo/config.rviz 실행
- [Rviz] Left camera - Depth, Right camera - Depth, Left camera - RGB, Right camera - RGB 체크하여 활성화 하면 각각의 윈도우가 뜸
- [new ST] rostopic pub /cmd_vel geometry_msgs/Twist '{linear:  {x: 0.0, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.2}}' 명령을 실행해 robot 의 회전각을 바꾸어 봄
- Rviz 에서 킨 window들과 Isaac-sim 의 camera window들이 회전하면 성공!
