### ISSUE TITLE
Isaac-sim + ROS navigation tutorial test

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#36]
# 설치해야되는 것
```shell
sudo apt install ros-melodic-acml
sudo apt install ros-melodic-map-server
sudo apt install ros-noetic-teleop-twist-keyboard
```
# 돌리고 있는 상황
1. roscore : server local
2. rospkg code : server local
3. isaac-sim : docker container

**Comment by eunji9128** [comment]
## 사전 준비


### ROS bridge + Isaac-sim docker 준비(아래 링크 사전 준비와 같음)
- https://github.com/ChaejinE/HanComTermProject/issues/34#issue-959131845
- 위 포스트의 설치해야 되는 것들 server com에 설치

## ROS Navigation 예제 실행


### Isaac-sim 에서 예제 실행
- 위에서 실행했던 Isaac-sim UI에서 예제 실행
  - Isaac Examples -> Communicating -> ROS -> Navigation
- 왼쪽 Play 실행


### map 제작
- Isaac-sim UI에서 viewport 왼쪽 상단의 carter_camera_stereo_left 클릭 후 dropdown 메뉴에서 Top 선택
- 상단 메뉴에서 Isaac Utils -> Occupancy Map 클릭
- map parameter를 아래와 같이 설정
- ![image](https://docs.omniverse.nvidia.com/app_isaacsim/_images/isaac_sample_ros_nav_2.png)
- Generate Occupancy Map 클릭
- 클릭 후 오른쪽 dropdown menu에서 0도를 180도로 변경
- Generate Image 클릭
- Visualization popup 뜨는 것 확인
- 팝업창에서 dropdown menu를 YAML 타입으로 변경
- Save Image 선택
- /home? root?/job_in_docker 안에 carter_warehouse_navigation.png 로 저장
- 팝업창 필드에 있는 텍스트 전체 선택 후 복사
- server com에서 새로운 터미널 오픈
- ```cd ~/catkin_ws/src/ros_samples/carter_2dnav/map```
- ```gedit carter_warehouse_navigation.yaml```
- 복사한 텍스트로 .yaml 파일 내용 대체 후 저장
- 맵 이미지 job_in_docker에서 workspace package로 이동
- ```mv ~/job_in_docker/carter_warehouse_navigation.png ~/catkin_ws/src/ros_samples/carter_2dnav/map/```


### ROS launch 실행(map 연동을 위한 소스)
- server com에서 새로운 터미널 오픈
- catkin_make, source devel/setup.bash 다 해줌
- roslaunch 실행
  - ```roslaunch carter_2dnav move_base.launch```
- Rviz 오픈 확인
- 로컬 맵과 월드 맵의 초기 위치를 대략적으로 맞춰주기 위해 Rviz 상단의 2D Pose Estimate 클릭하여 Pose Estimate 시켜줌
- ![image](https://docs.omniverse.nvidia.com/app_isaacsim/_images/isaac_sample_ros_nav_5.gif)


### tele op 실행(로봇 주행 수동 조작)
- server com에서 새로운 터미널 오픈
- tele op 실행
  - ```rosrun teleop_twist_keyboard teleop_twist_keyboard.py```
- 아래와 같이 수동 조작
- ![image](https://docs.omniverse.nvidia.com/app_isaacsim/_images/isaac_sample_ros_nav_6.gif)
- Rviz 상단 2D Nav Goal을 눌러 목적지 설정
- ![image](https://docs.omniverse.nvidia.com/app_isaacsim/_images/isaac_sample_ros_nav_7.gif)

**Comment by eunji9128** [comment]
sudo apt-get install ros-melodic-navigation
필수!

**Comment by eunji9128** [comment]
![image](https://user-images.githubusercontent.com/80051721/130820036-562c605f-13b4-4308-8725-8aa3964ac1ed.png)
