### ISSUE TITLE
21. 6. 25 하고 있는 거

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#4]
```shell
# docker gui 들어가서 설정
DOCKER_GUI_ATTACH
apt update && apt install git curl gedit nautilus wget -y
```

**Comment by ChaejinE** [comment]
```shell
git clone https://github.com/JinFree/OpenCV_in_Ubuntu
cd OpenCV_in_Ubuntu
gedit Install_OpenCV4_in_Ubuntu20.04.sh
```
- sh 파일에서 sudo 전부 삭제 (Docker 에서는 sudo 사용할 필요 X 때문)
```shell
./Install_OpenCV4_in_Ubuntu20.04.sh

**Comment by eunji9128** [comment]
DOCKER_GUI_ATTACH
apt update
apt install git curl gedit nautilus wget -y
nautilus # GUI 확인
git clone https://github.com/JinFree/darknet # darknet github clone, 기 설치 시 생략 가능
git clone https://github.com/JinFree/opencv_in_ubuntu # openCV for GPU github clone, 기 설치 시 생략 가능
cd OpenCV_in_Ubuntu/
gedit Install_OpenCV4_in_Ubuntu20.04.sh
(geditting..)
   remove 'sudo' from all lines
chmod +x Install_OpenCV4_in_Ubuntu20.04.sh
./Install_OpenCV4_in_Ubuntu20.04.sh

**Comment by ChaejinE** [comment]
```shell
pkg-config opencv4 --cflags
```
- opencv 설치 확인
```shell
cd darknet
gedit Makefile
```
- Makefile 수정
- CUDA 다운로드해서 CUDNN = 1 해도 되고 없으면 0
- https://developer.nvidia.com/rdp/cudnn-download
- Download cuDNN v8.2.1 (June 7th, 2021), for CUDA 11.x

![image](https://user-images.githubusercontent.com/69780812/123363681-fddb5380-d5ad-11eb-97a2-6836bccc00af.png)
- Download
```shell
cd Downloads && cp libcudnn8* ~/job_in_docker/.
```
- 공유 폴더 (job_in_docker)로 다운로드 받은 것을 copy
dpkg -i libcudnn8_8~~~
dpkg -i libcudnn8-dev~~~
![image](https://user-images.githubusercontent.com/69780812/123365192-c4581780-d5b0-11eb-837b-92a4830ec305.png)

**Comment by ChaejinE** [comment]
- 도커 영상 디스플레이 안됐어서 다시 컨테이너 올려야 할듯 ..
- https://smprlab.tistory.com/32

**Comment by ChaejinE** [comment]
빨리 올려주세요 궁금합니다.

**Comment by eunji9128** [comment]
------------------------------------------ 다시 컨테이너 시작 -----------------------------------------------------
[DOCKER_GUI.txt](https://github.com/ChaejinE/HanComTermProject/files/6713914/DOCKER_GUI.txt)

DOCKER_GUI_CV install
'''
cd ~
vim ~/.bashrc
(in bashrc)
    alias part 복붙 from DOCKER_GUI.txt
source ~/.bashrc # or restart terminal
DOCKER_GUI_CV
'''
DOCKER_GUI_CV_ATTACH & openCV for GPU install
'''
DOCKER_GUI_CV_ATTACH
apt update
apt install curl git vim wget
git clone https://github.com/JinFree/darknet
git clone https://github.com/JinFree/opencv4_in_ubuntu
cd opencv4_in_ubuntu
vim Install_openCV4_in_ubuntu20.04.sh
(in .sh)
    sudo removed from all lines
chmod +x Install_openCV4_in_ubuntu20.04.sh
./Install_openCV4_in_ubuntu20.04.sh
'''

cuDNN install
(이미 cuDNN 공유 폴더에 있다는 가정하에, 상단 채진 글 참조)
'''
cd /home/user/job_in_docker
dpkg -i libcudnn8_8.2.1.32-1+cuda11.3_amd64.deb # cuDNN runtime 먼저 설치
dpkg -i libcudnn8-dev_8.2.1.32-1+xuda11.3_amd64.deb
'''
Makefile 수정 & make
'''
cd ~/darknet
vim Makefile
(in Makefile)
    attach...
make
./darknet detector demo cfg/coco.data cfg/yolov4-tiny.cfg bin/yolov4-tiny.weights data/challenge.mp4
'''
