### ISSUE TITLE
받은 로봇 모델 움직이기

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#49]
# 목표
1. 아이작 심에서 AMR 움직여보기
2. 텔레옵적용
# 진행 순서
1. Physics 이해
2. Joint 및 Frame 맞춰보기
3. 구동 및 목표 구현

**Comment by chocoJiyeon** [comment]
1. Physics
중력 주기 - omniverse create

ground plane 을 넣어준 다음 stage 창에서 각각 물체들 마우스오른쪽 클릭
add --> physics --> rigid body with colliders preset 클릭
![image](https://user-images.githubusercontent.com/61004887/130166894-13e0b0a5-2f1f-43d7-9330-a32f41a92bdc.png)

그다음 rigid body 창에서 linear velocity 에 y축으로 -1해줌.
--> 이거 값을 -9.81로 해야하나???
![image](https://user-images.githubusercontent.com/61004887/130167079-9898375e-827d-451e-8dd8-a467c0deb3d9.png)

이렇게 하면 실행 눌렀을 때 모두 땅에 잘 떨어짐.

**Comment by ChaejinE** [comment]
오 감사감사
