### ISSUE TITLE
21. 6. 28 하고 있는거

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#5]
# # ros workspace 환경 구축
- https://github.com/katebrighteyes/ros_programming/blob/master/next2/readme.txt
```shell
cd
sudo apt-get install ros-melodic-image-transport ros-melodic-vision-msgs

./install_catkinws.sh dnn_ws
cd dnn_ws/src

git clone https://github.com/dusty-nv/ros_deep_learning

cd ..

catkin_make

source devel/setup.bash 

echo "source ~/dnn_ws/devel/setup.bash" >> ~/.bashrc

# VIEWER

roslaunch ros_deep_learning video_viewer.ros1.launch input:=/dev/video1 output:=display://0

# detection

roslaunch ros_deep_learning detectnet.ros1.launch input:=/dev/video1 output:=display://0
```
- ROS는 Yolo v3 까지만 지원한다고 한다. (논문을 V3 까지 읽어보는 것도 좋을 것 같아요)
- Master - Slave 일 때 == > IP setting이 중요하다고 합니다.

**Comment by ChaejinE** [comment]
bash 파일에 ros 올리는 스크립트 잊지 않기
# Car Slave, PC Master
- 192.168.102.20(Slave) - 192.168.102.10(Master) => SLAVE는 Master._.10  지정해줘야 한다. HOST는 자기 IP
  -  SLAVE: ROS_MASTER_URI = http://localhost(master ip):11311(port)
  -  ROS_HOSNAME=localhost(자기 ip)

**Comment by eunji9128** [comment]
![image](https://user-images.githubusercontent.com/80051721/123567584-75eb8880-d7fd-11eb-89cb-151b90f077e2.png)
![image](https://user-images.githubusercontent.com/80051721/123567627-91569380-d7fd-11eb-92be-1a1f934405d2.png)

video launch file 에서 source default 변경 가능

**Comment by ChaejinE** [comment]
# Lotto Team Logic Input / Output Design
## Object detection
- Frame -> detection net -> (x, y, w, h), label, confidence
## Classification
- Frame -> classification net -> label, confidence
## Line Tracking
- Frame -> lanedetect process
## Sensor Fusion
- Lidar, CAM, Encoder -> Kalman -> current_position

**Comment by eunji9128** [comment]
SLAM + EKF
[https://sunggoo.tistory.com/50](url)

**Comment by eunji9128** [comment]
![chart](https://user-images.githubusercontent.com/80051721/123588783-418ac300-d823-11eb-83bf-03ddbf971114.png)

**Comment by chocoJiyeon** [comment]
오늘 발표한거 피드백 & 질문답변

피드백
```
1. 세부 기능 test 단계별로 나눠서 생각하고 진행하기. (구현해야 할 기능이 너무 많아서)
2. 하드웨어 선정 잘하기 --> 이미 어느정도 되어있는 거로 시작하...?기..?
3. 화물 적재하는 거 실패하면 그냥 영상만 잘찍으면 되니까 / 화물 구상할 때 인지 잘되게 하기 
    실제 인식 시 시간 투자 많이 해야 할거니까 / 진짜 시간 없으면 색 다르게 해서라도 하기.
4. 너무 세부적인거에 휘둘리지 않고 / 큰 그림으로 적어도 단위단위는 기능 구현 되도록 잘 계획하기.(1번이랑 비슷한 말 같음)
5. 탈출 상황 인지할때 그냥 카메라로 하게 하면 됨.
6. collision avoidance 그냥 SLAM으로 하면 됨.
```
질문한거 답변
```
1. NX 보드를 사용해야 하는지? --> ㄴㄴ 자비에 달라고 하기. 여러대 요청해도 됨. 자비에 여러대 안되면 tx나 나노라도 달라고 해도 됨.
2. 보드 용량 부족 --> 보드에 sd카드 넣을 수 있음. SSD 넣을 수 있으면 좋은데 물어보기.
3. SLAM을 꼭 써야 하는지? --> SLAM 하면 좋은데 속도가 느려서 답답할수도 있음.  / 대안으로 line tracking 만 하면 빨라서 시간 안되면 이렇게 하기. 
4. 센서 퓨전 --> 자동차에서는 CAM + LiDAR 두개를 사용함. / CAM으로 이미지를 감지하고 - 목표에 대해 - 거리 계산을 하는데 - 이때 LiDAR로 거리를 체크한다(잘 되고 있는지 확인 차원) / 이렇게 칼만필터를 두개를 써서 한다?..
```
제가 기록한 바로는 이렇한데 잘못된 정보 있으면 고쳐주세요....

**Comment by chocoJiyeon** [comment]
> 오늘 발표한거 피드백 & 질문답변
> 
> 피드백
> 
> 1. 세부 기능 test 단계별로 나눠서 생각하고 진행하기. (구현해야 할 기능이 너무 많아서)
> 2. 하드웨어 선정 잘하기 --> 이미 어느정도 되어있는 거로 시작하...?기..?
> 3. 화물 적재하는 거 실패하면 그냥 영상만 잘찍으면 되니까 / 화물 구상할 때 인지 잘되게 하기
>    실제 인식 시 시간 투자 많이 해야 할거니까 / 진짜 시간 없으면 색 다르게 해서라도 하기.
> 4. 너무 세부적인거에 휘둘리지 않고 / 큰 그림으로 적어도 단위단위는 기능 구현 되도록 잘 계획하기.(1번이랑 비슷한 말 같음)
> 5. 탈출 상황 인지할때 그냥 카메라로 하게 하면 됨.
> 6. collision avoidance 그냥 SLAM으로 하면 됨.
> 
> 질문한거 답변
> 
> 1. TX 보드를 사용해야 하는지? --> ㄴㄴ 자비에 달라고 하기. 여러대 요청해도 됨. 자비에 여러대 안되면 NX나 나노라도 달라고 해도 됨.
> 2. 보드 용량 부족 --> 보드에 sd카드 넣을 수 있음. SSD 넣을 수 있으면 좋은데 물어보기.(SSD는 비싸서 안됨)
> 3. SLAM을 꼭 써야 하는지? --> SLAM 하면 좋은데 속도가 느려서 답답할수도 있음.  / 대안으로 line tracking 만 하면 빨라서 시간 안되면 이렇게 하기.
> 4. 센서 퓨전 --> 자동차에서는 CAM + LiDAR 두개를 사용함. / CAM으로 이미지를 감지하고 - 목표에 대해 - 거리 계산을 하는데 - 이때 LiDAR로 거리를 체크한다(잘 되고 있는지 확인 차원) / 이렇게 칼만필터를 두개를 써서 한다?..
> 
> 제가 기록한 바로는 이렇한데 잘못된 정보 있으면 고쳐주세요....

**Comment by ChaejinE** [comment]
왜 클로즈 합니까

**Comment by ChaejinE** [comment]
잘했어요
