### ISSUE TITLE
굴러가는 로봇 만들기

### ISSUE THREAD

**Issue by chocoJiyeon** [ChaejinE/HanComTermProject#50]
목표 : amr 이 안굴러가서 굴러갈 수 있게 만들기

**Comment by chocoJiyeon** [comment]
![image](https://user-images.githubusercontent.com/61004887/130032439-9607d7dd-fd47-440b-a66e-205b85ebf45e.png)
nvidia에서 카터 step파일 받을 수 있게 해놨다.
그래서 받았는데 100,686KB.....실화?

**Comment by chocoJiyeon** [comment]
우리는 들어야 하니까 위로 왔다갔다 하는 부품 추가! 
인벤터에서 step파일로 저장

![image](https://user-images.githubusercontent.com/61004887/130080379-24b5f7a8-dcc1-47f2-a368-cbb1b7d8d5af.png)

**Comment by chocoJiyeon** [comment]
3ds max에서 fbx로 저장해서 크리에이트에서 열었더니....
다 분리가 되서 ㅎㅎ.......ㅠㅠ 조립되서 넘어오게 해야할듯...

![image](https://user-images.githubusercontent.com/61004887/130086011-c96ce449-8e36-4425-a59f-7f12b7c62181.png)

**Comment by NamWoo** [comment]
강체 설정을 그냥 따로따로 해줬을때 불러오면 얘네들이 서로 서로가 붙어있는 애들이 아닌 그냥 충돌체, 서로 만나면 부딫혀야하는 애들인줄 알기 때문에 흩어지더라구용..

**Comment by NamWoo** [comment]
아참 참고로 얘 샘플로 옴니에 있어용~ ㅎㅎ 카터v2 라고 똑같아요!
