### ISSUE TITLE
Lottoworld_ver3 에 turtlebot3 주행하기

### ISSUE THREAD

**Issue by eunji9128** [ChaejinE/HanComTermProject#51]
- Lottoworld_ver3 올릴 때 translation 을 (0, 0, 0)으로 맞춰주지 않으면 맵 확대/축소가 안됨(버그 같음)
- Lottoworld_ver3(Ground plane 포함된 버전) 위에 주행 테스트를 위해 turtlebot3 올려봄
- turtlebot3 올릴 때 URDF Importer에서 joint drive type을 velocity로 바꿔주지 않으면 주행 불가
- 로봇 올리고 rear slider 추가 + collision 에서 friction min 으로 변경 안했을 때 > target velocity 변경해도 안 움직임
- rear slider 추가 + collision friction min으로 변경 했을 때 > target velocity 변경으로 주행 가능
- 맵 기둥에 부딪힘 확인, 롤테이너에 부딪힘 확인
- occupancy + SLAM 확인 예정

**Comment by NamWoo** [comment]
Lottoworld 환경에, turtlebot 올리고 아래 순서대로 확인하면 될거에용!

> 검증
> 주변 장애물에 잘 부딫히는지, 
> 가고자 하는 방향으로 잘 가는지, 이런..기준 설정!

* 1단계:  rosrun 에 텔레옵 키보드로 로봇 원하는 방향으로 움직이기
* 2단계:  ros launch 에 movebase 구동해서 rviz상 확인하기
  * occupancy map 저장해서 맞추기
  * ros topic 맞추기
* 3단계: 터틀봇에 없는 센서 넣기 ( ex 카메라)
  * 기존 라이다 센서 이리저리 가지고 놀아보기 (FOV, 분해능.. 바꿔보기)
  * 옴니에 카메라 넣고 토픽확인
  * rviz에서 옴니 카메라화면 받아오기
  * (extra:  urdf에 카메라 형태 만들어서 추가해서 올리기)
