### ISSUE TITLE
Nucleus local server 권한 이슈

### ISSUE THREAD

**Issue by eunji9128** [ChaejinE/HanComTermProject#52]
엔비디아에 문의 중
https://forums.developer.nvidia.com/t/problems-on-setting-up-local-nucleus-service/186795/2

**Comment by ChaejinE** [comment]
# 참조할 부분  
- https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/setup.html#Method%20#1:%20Package
# MyOrder
1. Nucleus uninstall -> Reboot
2. Nucleus install
3. localhost:8080, localhost:3080으로 연결 확인
4. Asset Download
5. Isaac sim > localhost 폴더 > Mouse Right Button > Make folder(Isaac)
6. 8080포트 > Mouse right Button > Upload
    - 다운로드받은 폴더들 여러개 있는데 하나씩 드래그하면서 decription 아무거나 적어서 넣어주시면됩니다..
    - ![asset-move](https://user-images.githubusercontent.com/69780812/130172845-6db5f6b0-19ca-4e83-bc70-95384d495130.gif)

**Comment by eunji9128** [comment]
https://github.com/teamlotto/Isaacsim/issues/1#issue-977774198

닫고 위 org 에서 tracking 할 예정
