### ISSUE TITLE
21. 6. 29 하고 있는거

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#6]
# 자이카 전원 키는법
- 자동차 배터리 전원 스위치 (BLue) -> USB 허브(Red) -> TX2 보드 전원 스위치(Green)
# 고용량 배터리
- 6 시간 충전 -> 8시간 사용
- 거의 안건드리는게 좋다. 전압 스위치가 있으니 12V 인지 확인 (Led 점등)
# 모터 배터리 충전
- 1 ~ 2 시간 충전 -> 2 ~ 4 시간 사용
- start  버튼으로 모드의  Setting값 조절할 수 있다.
- NiMH 로 설정 전류를 낮춰서 충전한다. -> 배터리를 고장 없이 오래 사용할 수 있다.
# 자이카 오픈 소스 커뮤니티
- https://vesc-project.com/

**Comment by ChaejinE** [comment]
# gvnc 설치
- https://developer.nvidia.com/embedded/learn/tutorials/vnc-setup

**Comment by ChaejinE** [comment]
# ROS
- 로봇 운영 체제
- Publishing( 메세지 보내는 쪽) Subscription(메세지 받는 쪽) Manager (Interaction Layer)
# 목표
- 어떤 언어로도 쉽게 구현 -> 로봇을 위한 코드들(다양한 언어) 재사용하기 위한 환경제공
- ROS만 설치되어있다면 이기종간 메시지 전송 가능
# 다양한 도구
- RVIZ
  - 센서 시각화에 용이
- RQT
  - 노드 연결정보를 graph로 시각화
- GAZEBO
  - 자신만의 시뮬레이터 제작 가능
 # 네트 워킹
- Roscore(master) 가 Node 들을 관리한다.
- 이기종 간에도 master는 하나여야하며 TCP/UDP로 통신한다.
# 용어
- Master : 노드간 통신 총괄
- Node : 통신 주체, 실행가능한 최소 단위 프로세스
- Topics : 주고 받는 메시지 (센서 데이터, 카메라 이미지 등)
- 발행자 노드 : 토픽을 만들어 보내는 노드
- 구독자 노드 : 토픽을 받는 노드 (모터 제어기 등)
- 패키지 : 하나 이상의 노드와 노드 싫애을 위한 정보 등을 묶은 것.
  - 하나 이상의 노드와 노드 실행을 위한 정보 등을 묶어 놓은 것 (녿, 라이브러리, 데이터 등이다.)

**Comment by ChaejinE** [comment]
# ROS Wiki 링크
- http://wiki.ros.org/Documentation

**Comment by eunji9128** [comment]
package : 특정 libraries, executables, scripts 등을 모아놓은 ROS 소프트웨어 유닛
manifest : package 의 정보를 담은 파일
rospack : package 의 위치 정보를 얻을 수 있는 명령어
```
rospack find [package name]
```
roscd : shell cd 와 같은 역할. package directory 로 이동하는 명령어
```
roscd [package or stack]
```
rosls : ros package 안의 내용 보여주는 명령어 = shell ls
```
rosls [package]
```
catkin package 는 해당 package의 메타 정보를 가지는 package.xml을 꼭 포함해야 한다
catkin package 는 CMakeList.txt 를 꼭 포함해야 한다
catkin package 는 각각 독립된 폴더에 저장되어야 한다(여러 package가 같은/하위 폴더 공유 불가능)

**Comment by ChaejinE** [comment]
find_package(catkin REQUIRED
        rospy
        std_msgs
        message_generation
)
