### ISSUE TITLE
21. 6. 30 하고 있는거 

### ISSUE THREAD

**Issue by eunji9128** [ChaejinE/HanComTermProject#7]
```
/usb_cam/image_raw + rplidarNode/scan + /imu_node/imu -> /auto_xycar -> /speed + /angle -> /car_driver
```
cam image + lidar scan + IMU value 의 값이 어떤 특정 상황일 때 motor angle/speed 를 어떻게 control 하겠다 라는 걸 실험값으로 정해줌
즉, 센서값들을 입력으로 받아 실험적 모터 컨트롤을 통해 주행 경로 설정

--> Line tracing은 이 개념으로 가능. Kalman 통한 자율 주행 경로 예측은.... 더 생각해봐야 할 듯

**Comment by eunji9128** [comment]
ROS node 설계에서
H/W, S/W 상관없이 node 로 표현, publisher/subscriber 개념으로 나타냄

**Comment by eunji9128** [comment]
자율주행로봇 참고 논문
http://www.koreascience.or.kr/article/CFKO201835372171386.pdf

**Comment by ChaejinE** [comment]
# laucnh
```shell
<launch>
        <node pkg="turtlesim" type="turtlesim_node" name="turtlesim_node"/>
        <node pkg="rospub" type="pub.py" name="pub_node"/>
        <node pkg="rossub" type="sun.py" name="sub_node" output="screen"/>
</launch>
```

**Comment by ChaejinE** [comment]
http://wiki.ros.org/ko/catkin/Tutorials/create_a_workspace

**Comment by raehak** [comment]
SLAM 위치 추정시 사용하는 Sensor : 엔코더 & 관성센서
참고 논문 : https://www.koreascience.or.kr/article/CFKO201735553776785.pdf

**Comment by ChaejinE** [comment]
string first_name
string last_name
int32 age
int32 score
string phone_number
int32 id_number

**Comment by ChaejinE** [comment]
# CMakeList.txt 수정
```
find_package(catkin REQUIRED
        rospy
        std_msgs
        message_generation
)

 add_message_files(
   FILES
   my_msg.msg
#   Message1.msg
#   Message2.msg
 )
```

**Comment by eunji9128** [comment]
http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeCppHydro
