### ISSUE TITLE
Linear Actuator HW 고민

### ISSUE THREAD

**Issue by ChaejinE** [ChaejinE/HanComTermProject#8]
- 어떻게 구현할지 ..
# 방법 1. Jetson PWM 구현 가능성 파악 (파악중)
- https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3243/index.html#page/Tegra%2520Linux%2520Driver%2520Package%2520Development%2520Guide%2Fhw_setup_jetson_io.html
- https://www.jetsonhacks.com/nvidia-jetson-xavier-nx-gpio-header-pinout/

**Comment by eunji9128** [comment]
Xavier controls servo motors
[https://jungeu1509.github.io/servomotor/NVIDIA_Jetson_AGX_Xavier/](url)

**Comment by ChaejinE** [comment]
# Linear Actuator 제어 방법
- https://www.firgelliauto.com/ko/blogs/tutorials/how-do-you-control-a-linear-actuator-with-an-arduino
- 1. 릴레이 스위치로  ON/OFF 제어로만 화물 적재를 할 수 있다.
- 2. 모터 드라이버 -> 리니어 액츄에이터의 속도를 조절하며 화물을 적재할 수 있다.

**Comment by ChaejinE** [comment]
할 필요 없어짐
