### ISSUE TITLE
21. 7. 05 하고 있는거

### ISSUE THREAD

**Issue by eunji9128** [ChaejinE/HanComTermProject#9]
### 이번 주 ROS programming 책에서 필수로 알아야 하는 내용!!
[chapter 3] ROS 기본 topic 사용법 --> 기본 중의 기본
[chapter 5] ROS action library --> action order 를 주고 feedback 을 받는 과정(ex. 목적지를 주고 그 곳에 도착하면 feedback 을 주도록 하는 명령) --> 이게 아마 우리 SLAM 때 목적지 이동에 쓰이는 기능일 듯..
[chapter 9 - 10] 세계 지도 구축 & 주행 --> 이 부분이 SLAM 과정인 듯
[chapter 15] 이미 드라이버가 잘 구축되어 있는 모터나 센서 등 ROS 용이 아닌 장치들을 ROS에서 쓸 수 있도록 S/W 설정하는 방법(어렵지 않고 함수 몇 개 만들어 주는 과정) 
[chapter 16] 아무것도 세팅되어 있지 않은 장치들을 ROS 에서 사용하기 위해 A-Z 까지 세팅하는 과정 이론 + 실습 --> 외부 장치들을 ROS에서 사용하도록 세팅하는 과정이 chapter 15 아니면 16일듯

**Comment by eunji9128** [comment]
VMware 6.0.8 install
VMware open
좌상단 파일 - 환경설정 - 확장 - (+) 클릭 - VMware extension 6.0.8 file 선택 후 확인

[도구 - 새로만들기]
이름 > ros
종류 > Linux
버전 > Ubuntu (64-bit)

만든 ros 가상 시스템 클릭
중상단 노란색 설정 클릭 후 아래와 같이 세팅

[디스플레이]
비디오 메모리 > max (option)
그래픽 컨트롤러 > VboxVGA
3차원 가속 사용하기 > enable

[시스템]
마더보드 - 칩셋 > ICH6 (option)
마더보드 - 기본메모리 > 4096 (초록색 max 하면 버벅거림)
프로세서 - CPU > 3 (option, 초록색 max 하면 버벅거림)
저장소 - 속성 - 종류 > ICH6 (option)

시작
3D objs 보이는 것 확인하면 성공

**Comment by ChaejinE** [comment]
안녕하세요 21학번 새내기 정채진입니다

**Comment by eunji9128** [comment]
코로나 악화로 인하여 21학번 입학은 연기 되었습니다. 돌아가.

**Comment by eunji9128** [comment]
노드 : 독립적으로 온전한 기능을 수행할 수 있는 하나의 프로그램

**Comment by ChaejinE** [comment]
# Work Space
- work space 만들기
``` shell
source /opt/ros/indigo.setup.bash
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src
catkin_init_workspace
cd ~/catkin_ws
catkin_make
```

**Comment by ChaejinE** [comment]
https://github.com/ChaejinE/HanComTermProject/wiki/%5BROS-%EC%9C%A0%EC%8B%A0%5D-ROS
오늘 유신 강사님 ROS 링크들
